name: CI

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -V
        pip install -e .[tests]
    - name: Run unit tests
      run: pytest -vx -rsx
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -V
        pip install -e .[lint]
    - name: Lint
      run: flake8
